//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Holiday.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int IdActivity { get; set; }
        public Nullable<int> IdModerator { get; set; }
        public Nullable<int> IdJuri { get; set; }
        public Nullable<int> Days { get; set; }
        public string ActivName { get; set; }
        public string Time { get; set; }
        public Nullable<int> IdPerson { get; set; }
        public Nullable<int> IdEvent { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Juri Juri { get; set; }
        public virtual Moderator Moderator { get; set; }
        public virtual Person Person { get; set; }
    }
}
